### ISSUE TITLE
pytest failing.

### ISSUE THREAD

**Issue by sbendarsky** [sbendarsky/flask#25]
==================================== short test summary info ==================================== 
FAILED tests/test_forms.py::test_submit_flying_form - assert b'Flying information submitted suc...
FAILED tests/test_forms.py::test_submit_driver_form - assert b'Driver information submitted suc...
============================ 2 failed, 3 passed, 6 warnings in 2.02s ==========================

**Comment by Daniel-Shwartzman** [comment]
fixed
